# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a079ea59506ad9aab9833bf3f58d48ec155e6933461053da08c90ec45377735e4bc942d23df245abffe54020604f44e1652fa64791607b2e6ff4a599fc8a0547

test:
  secret_key_base: 61c4a9e47d6628e0363e33a654423701d78c85450df2b08b872d0493f537873b238da4def34e0d502fd3ff7a668f11c4557efe1b7713dea3985a35a398ee042e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
